BULLPEN_FATIGUE = {
    "Arizona Diamondbacks": 5,
    "Atlanta Braves": 4,
    "Baltimore Orioles": 5,
    "Boston Red Sox": 6,
    "Chicago Cubs": 5,
    "Chicago White Sox": 7,
    "Cincinnati Reds": 6,
    "Cleveland Guardians": 4,
    "Colorado Rockies": 8,
    "Detroit Tigers": 5,
    "Houston Astros": 5,
    "Kansas City Royals": 6,
    "Los Angeles Angels": 7,
    "Los Angeles Dodgers": 4,
    "Miami Marlins": 7,
    "Milwaukee Brewers": 5,
    "Minnesota Twins": 5,
    "New York Mets": 6,
    "New York Yankees": 4,
    "Oakland Athletics": 7,
    "Philadelphia Phillies": 4,
    "Pittsburgh Pirates": 7,
    "San Diego Padres": 5,
    "San Francisco Giants": 6,
    "Seattle Mariners": 4,
    "St. Louis Cardinals": 5,
    "Tampa Bay Rays": 5,
    "Texas Rangers": 6,
    "Toronto Blue Jays": 5,
    "Washington Nationals": 7,
}