FIRST_INNING_RISK = {
    "Arizona Diamondbacks": 6,
    "Atlanta Braves": 7,
    "Baltimore Orioles": 6,
    "Boston Red Sox": 6,
    "Chicago Cubs": 6,
    "Chicago White Sox": 3,
    "Cincinnati Reds": 5,
    "Cleveland Guardians": 5,
    "Colorado Rockies": 5,
    "Detroit Tigers": 5,
    "Houston Astros": 6,
    "Kansas City Royals": 5,
    "Los Angeles Angels": 5,
    "Los Angeles Dodgers": 8,
    "Miami Marlins": 3,
    "Milwaukee Brewers": 5,
    "Minnesota Twins": 5,
    "New York Mets": 6,
    "New York Yankees": 8,
    "Oakland Athletics": 4,
    "Philadelphia Phillies": 7,
    "Pittsburgh Pirates": 4,
    "San Diego Padres": 6,
    "San Francisco Giants": 5,
    "Seattle Mariners": 5,
    "St. Louis Cardinals": 5,
    "Tampa Bay Rays": 5,
    "Texas Rangers": 6,
    "Toronto Blue Jays": 6,
    "Washington Nationals": 4,
}