TEAM_OFFENSE = {
    "Arizona Diamondbacks": 7,
    "Atlanta Braves": 8,
    "Baltimore Orioles": 7,
    "Boston Red Sox": 7,
    "Chicago Cubs": 7,
    "Chicago White Sox": 3,
    "Cincinnati Reds": 6,
    "Cleveland Guardians": 6,
    "Colorado Rockies": 5,
    "Detroit Tigers": 6,
    "Houston Astros": 7,
    "Kansas City Royals": 5,
    "Los Angeles Angels": 5,
    "Los Angeles Dodgers": 10,
    "Miami Marlins": 3,
    "Milwaukee Brewers": 6,
    "Minnesota Twins": 6,
    "New York Mets": 7,
    "New York Yankees": 9,
    "Oakland Athletics": 4,
    "Philadelphia Phillies": 8,
    "Pittsburgh Pirates": 4,
    "San Diego Padres": 7,
    "San Francisco Giants": 6,
    "Seattle Mariners": 6,
    "St. Louis Cardinals": 6,
    "Tampa Bay Rays": 6,
    "Texas Rangers": 7,
    "Toronto Blue Jays": 7,
    "Washington Nationals": 4,
}